export const adminStyles: Record<string, React.CSSProperties> = {
    page: {
      minHeight: '100vh',
      background: '#F7F4EF',
      padding: 24,
      fontFamily: 'Arial, sans-serif',
      color: '#1F2937',
    },
    centered: {
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: '#F7F4EF',
      color: '#1F2937',
      fontFamily: 'Arial, sans-serif',
    },
    card: {
      background: '#FFFFFF',
      border: '1px solid #D6D3D1',
      borderRadius: 20,
      padding: 20,
      boxShadow: '0 1px 2px rgba(0,0,0,0.06)',
    },
    title: {
      margin: 0,
      fontSize: 32,
      color: '#111827',
    },
    subtitle: {
      marginTop: 8,
      color: '#4B5563',
    },
    sectionTitle: {
      margin: 0,
      fontSize: 24,
      color: '#111827',
    },
    text: {
      color: '#374151',
      lineHeight: 1.6,
    },
    muted: {
      color: '#6B7280',
    },
    primaryButton: {
      background: '#1F6FEB',
      color: '#FFFFFF',
      border: 'none',
      borderRadius: 12,
      padding: '12px 16px',
      fontSize: 14,
      fontWeight: 700,
      cursor: 'pointer',
    },
    secondaryButton: {
      background: '#FFFFFF',
      color: '#111827',
      border: '1px solid #9CA3AF',
      borderRadius: 12,
      padding: '12px 16px',
      fontSize: 14,
      fontWeight: 700,
      cursor: 'pointer',
    },
    successButton: {
      background: '#15803D',
      color: '#FFFFFF',
      border: 'none',
      borderRadius: 12,
      padding: '12px 16px',
      fontSize: 14,
      fontWeight: 700,
      cursor: 'pointer',
    },
    warningButton: {
      background: '#B45309',
      color: '#FFFFFF',
      border: 'none',
      borderRadius: 12,
      padding: '12px 16px',
      fontSize: 14,
      fontWeight: 700,
      cursor: 'pointer',
    },
    dangerButton: {
      background: '#B91C1C',
      color: '#FFFFFF',
      border: 'none',
      borderRadius: 12,
      padding: '12px 16px',
      fontSize: 14,
      fontWeight: 700,
      cursor: 'pointer',
    },
    input: {
      padding: 12,
      borderRadius: 12,
      border: '1px solid #9CA3AF',
      fontSize: 16,
      color: '#111827',
      background: '#FFFFFF',
    },
    error: {
      color: '#B91C1C',
      margin: 0,
    },
  };